### ISSUE TITLE
Feature request: Add option to "share" artwork

### ISSUE THREAD

**Issue by utack** [devmil/muzei-bingimageoftheday#2]
Hi,  
Could you please consider adding a "share" button in this menu?
![screenshot_20180301-095646](https://user-images.githubusercontent.com/8551234/36835602-11419c82-1d37-11e8-967a-14b3f12d0a75.png)
The default "artwork" wallpaper has it, would it be possible to add it for Bing images too?
Ther eis an example of how it works in the national geographic plugin:
https://github.com/msal/muzei-nationalgeographic/blob/master/muzei-nationalgeographic/src/java/de/msal/muzei/nationalgeographic/NationalGeographicArtSource.java#L103
Thank you very much for consideration

**Comment by devmil** [comment]
Thanks for your feedback! This feature is part of version 1.3 that is published now

**Comment by utack** [comment]
Thank you, that was fast!

**Comment by devmil** [comment]
Glad to help. Always fun taking low hanging fruits to push the usability for users forward
