### ISSUE TITLE
Image tend to stuck after several days

### ISSUE THREAD

**Issue by yura-pakhuchiy** [devmil/muzei-bingimageoftheday#4]
Works great except it tends to stuck on the same image after several days of usage. Workaround to unstuck is to go to the plugin settings and then press back button, then it works again for several days.

**Comment by devmil** [comment]
Hi,
what device do you have and how often does this happen once a week or more once a month?

**Comment by yura-pakhuchiy** [comment]
Sony Xperia Z5, Android 7.1.1. Happens once in few days (once a week). I think it is
might be related to power saving features, because it seems never happen if
device is charging during wallpaper update time. However if device is not
charging during update time, it might get stuck and will not update anymore
unless I go to plugin settings.

**Comment by coreequip** [comment]
Same here.

- Mi Mix 2S
- MIUI10 / Android8
- All Battery savings disabled for Muzei, Autostart allowed

Issues like this are solved by the new [Muzei API 3.0](https://medium.com/@ianhlake/muzei-3-0-and-the-new-api-4fd3d6133db6). See #5 . 😃

**Comment by yura-pakhuchiy** [comment]
Seems to be be fixed in recent releases
