### ISSUE TITLE
Version 1.6 (7) in f-droid is not working

### ISSUE THREAD

**Issue by sultanahamer** [devmil/muzei-bingimageoftheday#6]
Muzei is saying "this plugin is not compatible with new api". I had to downgrade to Version 1.4 (5) and it is working.

**Comment by devmil** [comment]
Hi,

the problem is that Muzei hasn't been updated on F-Droid (but the Bing AddOn is automatically pushed to F-Droid).
Please contact the Muzei owner or install Muzei from the Google Play Store.

**Update**
Seems like a new update of Muzei is on its way. Should only be a matter of a day or so.
See here fore reference: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/net.nurik.roman.muzei.txt

**Comment by sultanahamer** [comment]
oh... thanks for the quick response. Will close this in that case.

**Comment by utack** [comment]
Stupid question:
How does one select Bing as source in the new Muzei
I am on Google Play, and can't see it either

**Comment by devmil** [comment]
Hi,

Bing Image of the Day should be in the normal plugins list. Does it simply not show up there? Did you install the latest version from Google Play?
Greetings
Michael

**Comment by utack** [comment]
Sorry, but where does one find the plugins list?
In the old version it is pretty clear where to find sources, in the new version I don't see it

**Comment by devmil** [comment]
Hi,

I have attached some screenshots. Does Muzei look similar on your device?

Greetings
Michael

**Comment by utack** [comment]
This is the screen I can not find any more
https://lh3.googleusercontent.com/1vZ-kthNXq3zQ50lDmZAIdOB1CI0FmtLY8EQZmJqD_WVFwqm8rEW56fUTAXETGus_w0=w3840-h1894

**Comment by devmil** [comment]
Sorry, didn't know that replying via E-Mail with attachments drops the attachments here.

This is how the screen should look:
![screenshot_20190215_235629_net nurik roman muzei](https://user-images.githubusercontent.com/6693130/52898633-53ceae00-31e0-11e9-85d4-cfd0a620891c.jpg)
![screenshot_20190215_235641_net nurik roman muzei](https://user-images.githubusercontent.com/6693130/52898637-5e894300-31e0-11e9-8877-9be7b77ffe5e.jpg)

**Comment by utack** [comment]
Ok i am really sorry, this almost comical at this point, but I still don't see it
I am initially greeted by this screen
How do I get to the one you are showing above?
![screenshot_2019-02-16-14-15-28-500_com android wallpaper livepicker](https://user-images.githubusercontent.com/8551234/52900376-630c2680-31f5-11e9-9c8c-e44331372078.png)

**Comment by devmil** [comment]
Tap on "Hintergrund festlegen" then Muzei is your background. After that you can change the Muzei settings (and e.g. choose the Plugin) in the Muzei app.
If you like you can contact me also directly via devmil [at] posteo [dot] de

**Comment by utack** [comment]
Wow thanks,that worked 🙏 
I was fixated on the old method where you choose the source upon setup

**Comment by devmil** [comment]
Great! So I think this issue is resolved
